### ISSUE TITLE
Go To Definition not working properly

### ISSUE THREAD

**Issue by Dynge** [iabdelkareem/csharp.nvim#10]
Hi

I am having issues with the Go To Definition function.
It works just fine for the local codebase - however when trying to open classes from other packages I get an `index out of range` error:

```txt
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1914: index out of range
stack traceback:
        [C]: in function '_str_byteindex_enc'
        /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1914: in function 'locations_to_items'
        /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:435: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Do you have any idea what this may be caused by?

Using:
```txt
NVIM v0.10.0-dev

omnisharp v1.39.11 (installed via Mason)
```

**Comment by matthew-nm** [comment]
I have this same issue when using the roslyn LSP. This functionality works as expected with roslyn other plugins such as https://github.com/seblj/roslyn.nvim.

EDIT: It actually seems hit-or-miss when I use the roslyn plugin linked above, so it might be more of a roslyn issue. But it does sometimes work.
