### ISSUE TITLE
How to disable certain hints?

### ISSUE THREAD

**Issue by loissascha** [iabdelkareem/csharp.nvim#17]
Hello,
first of all: your plugin is awesome! I always struggled to get omnisharp running and whenever I got it running it didn't work properly. So thank you very much for your awesome work! 

I have a question which I think is mostly related to me not knowing how to configure omnisharp, but I wasn't able to find anything on it.
I used the normal installation with lazy (pretty much copy & paste from your example installation) which uses omnisharp. Whenever I open one of my projects now (first of all I get actually working LSP stuff which is awesome thank you again!) I get a huge amount of inline hints telling me stuff like: "Convert to block scoped namespace, Use explicit type instead of 'var', ....". Some of them are very useful, others I don't like as much. Especially the 2 I named here as an example I don't like. I don't like block scoped namespace and I always use var instead of explicit types. I'm sure there is a way to disable or configure these hints but I can't find it. 

Can someone please help me with that?

**Comment by iabdelkareem** [comment]
Hi @loissascha , Thank you ^^ Glad you find the plugin useful. You can pick and choose which hints Omnisharp displays via the [omnisharp config file](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#roslyn-extensions-options).
