### ISSUE TITLE
🎁Enhancement: Dotnet user secrets

### ISSUE THREAD

**Issue by GustavEikaas** [iabdelkareem/csharp.nvim#6]
Expose some way to load secrets.json into a buffer.

e.g require("csharp").load_secrets()
Will prompt which project to open secrets for with a selector.
When choosing one, resolve the file and load into a new buffer

**Comment by danielcopper** [comment]
I made myself a small and really barebones telescope extension for this. If anyone is interested I can share it.

**Comment by iabdelkareem** [comment]
This feature is merged. Thanks to @jmartins-sh
